### ISSUE TITLE
Unable to play back purchased Youtube content

### ISSUE THREAD

**Issue by kylegordon** [bromix/plugin.video.youtube#243]
Unfortunately I'm unable to play back any paid content, such as purchased movies or channels (test cases being Drive+ (https://www.youtube.com/channel/UCfbPZ1cTgBH2djzLLCPTmXg) and Shaun The Sheep (https://www.youtube.com/watch?v=Z1abboEXMdA)

Whilst the items are available in the menus, the content itself refuses to play. I'm not sure if this is a known bug, or something that's not supported at all :-) 

If it helps, the logs that I'm getting are...

11:27:14 T:139695732279040  NOTICE: Thread LanguageInvoker start, auto delete: false
11:27:14 T:139695732279040  NOTICE: -->Python Interpreter Initialized<--
11:27:14 T:139695732279040  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0~beta1) on Helix (14.2) with Python 2.7.6
11:27:17 T:139695732279040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 299, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/var/lib/htpc//.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_play.py", line 24, in play_video
                                                if video_stream['format'].get('rtmpe', False):
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
11:27:17 T:139696475539392   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=JKy_zvLlDBo]
11:27:17 T:139695732279040  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by bromix** [comment]
Not supported by the APIv3 of YouTube and will probably never come.

**Comment by kylegordon** [comment]
No problem, good to know. Cheers
