### ISSUE TITLE
script crash viewing subscriptions

### ISSUE THREAD

**Issue by keis** [bromix/plugin.video.youtube#245]
The script crashes for me when trying to view my subscriptions. If I hack the script and remove the thumbnailImage parameter everything else works just fine.

```stacktrace
Error Type: <type 'exceptions.TypeError'>
Error Contents: argument "thumbnailImage" for method "XBMCAddon::xbmcgui::ListItem" must be unicode or str
Traceback (most recent call last):
  File "/storage/.xbmc/addons/plugin.video.youtube/default.py", line 7, in <module>
    runner.run(__provider__)
  File "/storage/.xbmc/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 16, in run
    __RUNNER__.run(provider, context)
  File "/storage/.xbmc/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 49, in run
    self._add_directory(context, item, item_count)
  File "/storage/.xbmc/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 95, in _add_directory
    thumbnailImage=directory_item.get_image())
TypeError: argument "thumbnailImage" for method "XBMCAddon::xbmcgui::ListItem" must be unicode or str
```

**Comment by bromix** [comment]
You're using an old version of xbmc. Please update you're system.

**Comment by keis** [comment]
yeah, looks like I have a pretty ancient version. I'll try updating. thanks

**Comment by bromix** [comment]
np ;)
