### ISSUE TITLE
Script Error opening "My Supscriptions"

### ISSUE THREAD

**Issue by bluezed** [bromix/plugin.video.youtube#253]
When trying to open the "My Subscriptions" section I'm getting a script error.

Here the details in the log:
```
21:19:48 T:2388147008  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0) on Helix (14.2) with Python 2.7.6
21:19:48 T:2388147008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 355, in _on_yt_specials
                                                return yt_specials.process(category, self, context, re_match)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py", line 223, in process
                                                return _process_new_uploaded_videos(provider, context, re_match)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py", line 57, in _process_new_uploaded_videos
                                                json_data = provider.get_client(context).get_uploaded_videos_of_subscriptions(start_index)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 78, in get_uploaded_videos_of_subscriptions
                                                params=params)
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 615, in _perform_v2_request
                                                return result.json()
                                              File "/home/tv/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 44, in json
                                                return real_json.loads(self.text)
                                              File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
21:19:48 T:3032196928   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos/
21:19:48 T:3032196928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos/) failed
```

**Comment by bromix** [comment]
Please delete the cache and reinstall the addon again. The path is completely wrong. It must be **new_uploaded_videos_tv**

**Comment by bluezed** [comment]
Thank you, it's working again now.
