### ISSUE TITLE
unable to play specific video ('NoneType' object has no attribute '__getitem__')

### ISSUE THREAD

**Issue by spanktastic2120** [bromix/plugin.video.youtube#302]
For whatever reason this specific video isnt getting parsed right and the addon ends up with an empty object. Video in question: https://www.youtube.com/watch?v=Mwbf9mC9Whk

Relevant error from log:
```
Error Type: <type 'exceptions.TypeError'>
Error Contents: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\default.py", line 7, in <module>
    runner.run(__provider__)
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\resources\lib\kodion\runner.py", line 16, in run
    __RUNNER__.run(provider, context)
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\resources\lib\kodion\impl\xbmc\xbmc_runner.py", line 27, in run
    results = provider.navigate(context)
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\resources\lib\kodion\abstract_provider.py", line 106, in navigate
    result = method(context, re_match)
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\resources\lib\kodion\register_provider_path.py", line 12, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\resources\lib\youtube\provider.py", line 241, in _on_play
    return yt_play.play_video(self, context, re_match)
  File "C:\Users\Billy\AppData\Roaming\XBMC\addons\plugin.video.youtube\resources\lib\youtube\helper\yt_play.py", line 21, in play_video
    video_item = VideoItem(video_id, video_stream['url'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```
The error occurs whether being played from the Watch Later list or by searching for the video, if that is relevant. I tested it on two machines both using XBMC v13.2, one with Windows the other with Linux.

**Comment by spanktastic2120** [comment]
Nevermind, wasnt using the latest version.
