### ISSUE TITLE
Toasts instead of popups when video is not available

### ISSUE THREAD

**Issue by Razzeee** [bromix/plugin.video.youtube#303]
Would it be possible to get toasts/notifications about a playback gone wrong and not a popup? I'm often getting stuck with an popup over the next queued video and when I try to close that it always shuts down the whole playback/playlist.

**Comment by bromix** [comment]
No, the API of KODI doesn't provide "Toasts"..It's skin depended.

**Comment by Razzeee** [comment]
http://kodi.wiki/view/List_of_built-in_functions

```Notification(header,message[,time,image])```

**Comment by bromix** [comment]
Thats exactly what I'm using ;) ! That's the popup you see...nothing I can do about it
https://github.com/bromix/plugin.video.youtube/blob/master/resources/lib/youtube/helper/v3.py#L238

Try this skin...it makes Toasts
http://forum.kodi.tv/showthread.php?tid=229069

**Comment by Razzeee** [comment]
@bromix 
Thank you, something seems to be wrong with my setup then. Maybe I'm still stuck on an old youtube version, as it is definatly a popup opening and the string being shown is not in your strings.po
I'll report back, when I can test at home.

**Comment by bromix** [comment]
okay? Can you make a screenshot?

**Comment by Razzeee** [comment]
I will as soon as I'm back home in about 10 hours.

**Comment by bromix** [comment]
:+1:  ;)

**Comment by Razzeee** [comment]
Sorry, for the confusion, I couldn't force it to happen.
Maybe it's gone the issue was more of, "well this bothered me for months, I should probably finally bring this to attention" and not "I just ran into this"
If it happens again, I will create a screenshot and save the logfile. Thank you.

**Comment by bromix** [comment]
Okay ;) and thanks for your feedback.

**Comment by Razzeee** [comment]
It just came up again, I think my network did go down for some reason when this happend. Seemed to be at the same time the video tried to start.

```
00:12:11 T:1570763840  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.7) on Helix (14.2) with Python 2.7.3
00:12:20 T:1616925760   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
00:12:20 T:1616925760   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
00:12:30 T:1616925760   ERROR: Open - failed to open source <http://mirrors.kodi.tv/addons/gotham/addons.xml.md5>
00:12:30 T:1616925760   ERROR: Failed to fetch checksum for directory listing http://mirrors.kodi.tv/addons/gotham/addons.xml for repository repository.xbmc.org.
00:12:31 T:1570763840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 363, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_play.py", line 17, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 80, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/video_info.py", line 313, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/video_info.py", line 518, in _method_get_video_info
                                                result = requests.get(url, params=params, headers=headers, verify=False, allow_redirects=True)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 179, in get
                                                return _request('GET', url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 155, in _request
                                                response = opener.open(request)
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1215, in https_open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--
```
Full log:
http://xbmclogs.com/p2spx9mof
