### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by geniuslwf** [bromix/plugin.video.youtube#331]
I've met this exception multiple times, which prevented me from using the plugin:

01:31:59 T:1837845192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: database is locked
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 157, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 487, in on_root
                                                self.get_client(context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 101, in get_client
                                                context.get_function_cache().clear()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/function_cache.py", line 22, in clear
                                                self._clear()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/storage.py", line 150, in _clear
                                                self._execute(True, query)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/storage.py", line 79, in _execute
                                                return self._cursor.execute(query, values)
                                            OperationalError: database is locked
                                            -->End of Python script error report<--

**Comment by geniuslwf** [comment]
This seems to be caused by kodi crashing in the middle of video playing. After kodi crashed, the next time I try to open youtube plugin it would fail to open. It should fail more gracefully, like delete the sqllite database file and recreate a new one when this happens.

**Comment by geniuslwf** [comment]
I'm using kodi 15.1, youtube plugin 5.1.9

**Comment by bromix** [comment]
If it's looked then i can't even delete the file ;)

The crash from the playback shouldn't happen. If possible try to provide a log after a playback fails.

**Comment by geniuslwf** [comment]
That's the full log file:

https://dl.dropboxusercontent.com/u/8681257/kodi.old.log

The exception happened at line 534,  646 and 757

**Comment by geniuslwf** [comment]
perhaps roll to a different file name if it's locked? like cache.sqlite to cache1.sqlite, then to cache2.sqlite...

**Comment by geniuslwf** [comment]
It happened again for my girlfriend's TV android box... After deleting the sqlite file it's working again.
