### ISSUE TITLE
plugin not showing any video

### ISSUE THREAD

**Issue by vilorious** [bromix/plugin.video.youtube#332]
Is it just me or are there some Issues lately. I cannot play any Videos but I can log in and everything else. Can anybody confirm if it is a problem or just me. Thanks a lot!

My System: YouTube Addon (5.1.8) on Frodo (12.3) with Python 2.7.3 (on Pi)

Sadly I don´t really understand the log:
>16:28:08 T:2896163904  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.8) on Frodo (12.3) with Python 2.7.3
16:28:09 T:2563593280  NOTICE: Thread Background Loader start, auto delete: false
16:28:15 T:2896163904  NOTICE: Thread XBPyThread start, auto delete: false
16:28:15 T:2896163904  NOTICE: -->Python Interpreter Initialized<--
16:28:18 T:2896163904  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.8) on Frodo (12.3) with Python 2.7.3
16:28:31 T:2896163904  NOTICE: Thread Background Loader start, auto delete: false
16:28:42 T:2896163904  NOTICE: Thread XBPyThread start, auto delete: false
16:28:42 T:2896163904  NOTICE: -->Python Interpreter Initialized<--
16:28:44 T:2896163904  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.8) on Frodo (12.3) with Python 2.7.3
16:28:45 T:2896163904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'title'
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/youtube/provider.py", line 363, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/youtube/helper/yt_play.py", line 17, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/pi/.xbmc/addons/plugin.video.youtube-master/resources/lib/youtube/client/youtube.py", line 85, in get_video_streams
                                                video_stream['title'], video_stream['container'], video_stream['video']['encoding'],
                                            KeyError: 'title'
                                            -->End of Python script error report<--
16:28:46 T:3040169984   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=CfXeSNXECMw]

**Comment by bromix** [comment]
Please no logs here. Logs only via pastebin.com or similar services.
Update the addon to 5.1.9
Also keep in mind Frodo isn't supported anymore

**Comment by bromix** [comment]
And the bug is fixed in 5.1.9 ;)

**Comment by vilorious** [comment]
Sorry and Thanks a lot! And of cource thank you very much for this amazing addon!!! Great Work!

**Comment by vilorious** [comment]
and it works like a charme again (on Frodo)!!! So thanks as well for this fast fix  :) Very nice work!
